"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import hashlib
import os
import warnings
from pathlib import Path

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover
    load_dotenv = None

try:
    import dj_database_url
except ImportError:  # pragma: no cover
    dj_database_url = None

try:
    import cloudinary
except ImportError:  # pragma: no cover
    cloudinary = None

try:
    from sklearn.exceptions import InconsistentVersionWarning
except Exception:  # pragma: no cover
    InconsistentVersionWarning = None

if InconsistentVersionWarning is not None:
    # Reduce runtime log noise from persisted sklearn model version metadata mismatch.
    warnings.filterwarnings("ignore", category=InconsistentVersionWarning)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
if load_dotenv is not None:
    load_dotenv(BASE_DIR / ".env")


def _get_env(*names: str, default: str | None = None) -> str | None:
    for name in names:
        value = os.getenv(name)
        if value is not None:
            return value
    return default


def _get_bool_env(*names: str, default: bool = False) -> bool:
    value = _get_env(*names)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _get_list_env(*names: str, default: str = "") -> list[str]:
    value = _get_env(*names, default=default) or ""
    return [item.strip() for item in value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _get_env(
    "SECRET_KEY",
    "DJANGO_SECRET_KEY",
    default="unsafe-dev-key-change-me-please-set-django-secret-key",
)


def _resolve_jwt_signing_key() -> str:
    configured_key = os.getenv("JWT_SIGNING_KEY")
    if configured_key:
        return configured_key

    if len(SECRET_KEY.encode("utf-8")) >= 32:
        return SECRET_KEY

    # PyJWT recommends at least 32 bytes for HS256 keys. When local env vars
    # are missing, derive a deterministic dev-only key instead of warning.
    return hashlib.sha256(SECRET_KEY.encode("utf-8")).hexdigest()


JWT_SIGNING_KEY = _resolve_jwt_signing_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _get_bool_env("DEBUG", "DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = _get_list_env(
    "ALLOWED_HOSTS",
    "DJANGO_ALLOWED_HOSTS",
    default="localhost,127.0.0.1",
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'channels',
    'rest_framework',
    'corsheaders',
    "django_extensions",
    
    # Local apps
    'users_app.apps.UsersAppConfig',
    "quizzes_app",
    "analytics_app",
    "dashboards_app",
    "ai_service",
    "courses",
    "analytics_ai",
    
]

AUTH_USER_MODEL = 'users_app.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # protect endpoints
    ],
}

SIMPLE_JWT = {
    "SIGNING_KEY": JWT_SIGNING_KEY,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = _get_env("DATABASE_URL")

if DATABASE_URL and dj_database_url is not None:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': os.getenv('POSTGRES_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.getenv('POSTGRES_DB', 'enhance_lms'),
            'USER': os.getenv('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
            'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
SERVE_MEDIA_FILES = _get_bool_env("SERVE_MEDIA_FILES", default=True)

CLOUDINARY_CLOUD_NAME = _get_env("CLOUDINARY_CLOUD_NAME")
CLOUDINARY_API_KEY = _get_env("CLOUDINARY_API_KEY")
CLOUDINARY_API_SECRET = _get_env("CLOUDINARY_API_SECRET")
CLOUDINARY_AVATARS_ENABLED = bool(
    cloudinary is not None
    and CLOUDINARY_CLOUD_NAME
    and CLOUDINARY_API_KEY
    and CLOUDINARY_API_SECRET
)

if CLOUDINARY_AVATARS_ENABLED:
    cloudinary.config(
        cloud_name=CLOUDINARY_CLOUD_NAME,
        api_key=CLOUDINARY_API_KEY,
        api_secret=CLOUDINARY_API_SECRET,
        secure=True,
    )

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CORS_ALLOWED_ORIGINS = _get_list_env(
    "CORS_ALLOWED_ORIGINS",
    "DJANGO_CORS_ALLOWED_ORIGINS",
    default="http://localhost:3000,http://127.0.0.1:3000",
)

CORS_ALLOW_ALL_ORIGINS = False

CSRF_TRUSTED_ORIGINS = _get_list_env(
    "CSRF_TRUSTED_ORIGINS",
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    default="http://localhost:3000,http://127.0.0.1:3000",
)


if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = _get_bool_env("SECURE_SSL_REDIRECT", default=True)
    SESSION_COOKIE_SECURE = _get_bool_env("SESSION_COOKIE_SECURE", default=True)
    CSRF_COOKIE_SECURE = _get_bool_env("CSRF_COOKIE_SECURE", default=True)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_REFERRER_POLICY = "same-origin"


CHANNEL_LAYER_BACKEND = os.getenv("DJANGO_CHANNEL_LAYER_BACKEND", "memory").strip().lower()
if CHANNEL_LAYER_BACKEND == "redis":
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [os.getenv("DJANGO_CHANNEL_REDIS_URL", "redis://127.0.0.1:6379/0")],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


EMAIL_HOST = _get_env("EMAIL_HOST", "DJANGO_EMAIL_HOST", default="")
EMAIL_PORT = int(_get_env("EMAIL_PORT", "DJANGO_EMAIL_PORT", default="587") or 587)
EMAIL_HOST_USER = _get_env("EMAIL_HOST_USER", "DJANGO_EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = _get_env("EMAIL_HOST_PASSWORD", "DJANGO_EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = _get_bool_env("EMAIL_USE_TLS", "DJANGO_EMAIL_USE_TLS", default=True)
DEFAULT_FROM_EMAIL = _get_env("DEFAULT_FROM_EMAIL", "DJANGO_DEFAULT_FROM_EMAIL", default="no-reply@enhancelms.local")
FRONTEND_URL = _get_env("FRONTEND_URL", "DJANGO_FRONTEND_URL", default="http://localhost:3000")
PASSWORD_RESET_TIMEOUT = int(_get_env("PASSWORD_RESET_TIMEOUT", "DJANGO_PASSWORD_RESET_TIMEOUT", default="259200") or 259200)

if EMAIL_HOST and EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = _get_env("DJANGO_EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
else:
    EMAIL_BACKEND = _get_env("DJANGO_EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")


CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "memory://")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "cache+memory://")
CELERY_TASK_ALWAYS_EAGER = os.getenv("CELERY_TASK_ALWAYS_EAGER", "true" if DEBUG else "false").strip().lower() == "true"
CELERY_TASK_EAGER_PROPAGATES = os.getenv("CELERY_TASK_EAGER_PROPAGATES", "true" if DEBUG else "false").strip().lower() == "true"
