# Generated by Django 5.2.7 on 2025-12-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseactivity',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='activities/'),
        ),
        migrations.AddField(
            model_name='courseactivity',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
