# Generated by Django 5.2.7 on 2026-02-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_submissionattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.FloatField(default=0)),
                ('requires_points', models.BooleanField(default=True)),
                ('requires_due_date', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='courseactivity',
            name='activity_type',
            field=models.CharField(max_length=50),
        ),
    ]
