# Generated by Django 5.2.7 on 2026-02-26 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_activitytype_alter_courseactivity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseactivity',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.activitytype'),
        ),
    ]
