# Generated by Django 5.2.7 on 2026-02-26 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_courseactivity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionattachment',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.courseactivity'),
        ),
        migrations.AlterField(
            model_name='submissionattachment',
            name='file',
            field=models.FileField(upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='submissionattachment',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.activitysubmission'),
        ),
    ]
