# Generated by Django 5.2.7 on 2026-02-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_submissionattachment_announcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseactivity',
            name='grading_type',
            field=models.CharField(choices=[('points', 'Points'), ('percent', 'Percentage'), ('passfail', 'Pass/Fail'), ('none', 'Ungraded')], default='points', max_length=20),
        ),
        migrations.AddField(
            model_name='courseactivity',
            name='question_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courseactivity',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
