# Generated by Django 5.2.7 on 2026-03-17 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_drop_quizattempt_quiz_student_unique'),
        ('users_app', '0011_user_instructor_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_type', models.CharField(choices=[('zero_based', 'Zero-based'), ('transmuted', 'Transmuted'), ('custom', 'Custom')], default='zero_based', max_length=20)),
                ('passing_grade', models.FloatField(default=75)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_scheme', to='users_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='GradingComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('weight', models.FloatField()),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='courses.gradingscheme')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
