# Generated by Codex on 2026-03-17

from django.db import migrations


def seed_exam_project_activity_types(apps, schema_editor):
    ActivityType = apps.get_model("courses", "ActivityType")

    required_types = [
        {"name": "Exam", "weight": 0, "requires_points": True, "requires_due_date": True},
        {"name": "Project", "weight": 0, "requires_points": True, "requires_due_date": True},
    ]

    for item in required_types:
        existing = ActivityType.objects.filter(name__iexact=item["name"]).first()
        if existing:
            continue
        ActivityType.objects.create(**item)


def noop_reverse(apps, schema_editor):
    # Keep seeded activity types on rollback to avoid removing user data dependencies.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0019_gradingscheme_gradingcomponent"),
    ]

    operations = [
        migrations.RunPython(seed_exam_project_activity_types, noop_reverse),
    ]
