# Generated by Django 5.2.7 on 2026-03-17 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_seed_exam_project_activity_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseactivity',
            name='assessment_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('exam', 'Exam')], default='quiz', max_length=10),
        ),
        migrations.AddField(
            model_name='courseactivity',
            name='availability_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseactivity',
            name='availability_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseactivity',
            name='project_group_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseactivity',
            name='randomize_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=20),
        ),
        migrations.CreateModel(
            name='GradingComponentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='courses.gradingcomponent')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['component_id', 'student_id'],
                'unique_together': {('component', 'student')},
            },
        ),
    ]
