# Generated by Codex on 2026-03-18

from django.db import migrations


def seed_core_classwork_types(apps, schema_editor):
    ActivityType = apps.get_model("courses", "ActivityType")

    required = [
        {"name": "Assignment", "requires_points": True, "requires_due_date": True},
        {"name": "Quiz", "requires_points": True, "requires_due_date": True},
        {"name": "Material", "requires_points": False, "requires_due_date": False},
        {"name": "Project", "requires_points": True, "requires_due_date": True},
    ]

    for entry in required:
        existing = ActivityType.objects.filter(name__iexact=entry["name"]).first()
        if existing:
            if existing.requires_points != entry["requires_points"] or existing.requires_due_date != entry["requires_due_date"]:
                existing.requires_points = entry["requires_points"]
                existing.requires_due_date = entry["requires_due_date"]
                existing.save(update_fields=["requires_points", "requires_due_date"])
            continue
        ActivityType.objects.create(weight=0, **entry)


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0021_courseactivity_assessment_type_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_core_classwork_types, migrations.RunPython.noop),
    ]
