# Generated by Django 5.2.7 on 2026-03-19 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_seed_core_classwork_types'),
        ('users_app', '0011_user_instructor_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseactivity',
            name='assigned_courses',
            field=models.ManyToManyField(blank=True, related_name='assigned_activities', to='users_app.course'),
        ),
        migrations.AddField(
            model_name='courseactivity',
            name='publish_state',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=12),
        ),
        migrations.AddField(
            model_name='courseactivity',
            name='quiz_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ClassworkDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('assessment_type', models.CharField(choices=[('quiz', 'Quiz'), ('exam', 'Exam')], default='quiz', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('availability_start', models.DateTimeField(blank=True, null=True)),
                ('availability_end', models.DateTimeField(blank=True, null=True)),
                ('points', models.IntegerField(default=100)),
                ('quiz_time_limit_seconds', models.PositiveIntegerField(default=1800)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('randomize_questions', models.BooleanField(default=False)),
                ('topic', models.CharField(blank=True, default='', max_length=100)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('course_ids', models.JSONField(blank=True, default=list)),
                ('imported_source_name', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classwork_drafts', to='users_app.course')),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='classwork_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
