# Generated by Django 5.2.7 on 2026-03-21 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_courseactivity_assigned_courses_and_more'),
        ('users_app', '0011_user_instructor_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseactivity',
            name='anti_cheat_disable_copy_paste',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseactivity',
            name='anti_cheat_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseactivity',
            name='anti_cheat_fullscreen_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseactivity',
            name='anti_cheat_multi_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseactivity',
            name='anti_cheat_tab_switch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseactivity',
            name='random_subset_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseactivity',
            name='randomize_choices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseactivity',
            name='require_answer_to_advance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='suspicious_events',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QuestionBankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, default='', max_length=120)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=12)),
                ('question_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_items', to='users_app.course')),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuizSecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('multiple_tab', 'Multiple Tab'), ('copy_attempt', 'Copy Attempt'), ('paste_attempt', 'Paste Attempt'), ('fullscreen_exit', 'Fullscreen Exit')], max_length=40)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to='courses.quizattempt')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to='courses.courseactivity')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
