# Generated by Django 5.2.7 on 2026-03-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_courseactivity_anti_cheat_disable_copy_paste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classworkdraft',
            name='anti_cheat_disable_copy_paste',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classworkdraft',
            name='anti_cheat_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classworkdraft',
            name='anti_cheat_fullscreen_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classworkdraft',
            name='anti_cheat_multi_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classworkdraft',
            name='anti_cheat_tab_switch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classworkdraft',
            name='random_subset_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classworkdraft',
            name='randomize_choices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classworkdraft',
            name='require_answer_to_advance',
            field=models.BooleanField(default=False),
        ),
    ]
