# Generated by Django 5.2.7 on 2026-03-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_merge_0027_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='force_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='lock_reason',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
