# Generated by Django 5.2.7 on 2026-03-27 03:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_quizattempt_force_submitted_at_quizattempt_is_locked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classworkdraft',
            name='pre_exam_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='QuizAttemptAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ack_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ack_message', models.TextField(blank=True, default='')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='courses.quizattempt')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_acknowledgements', to='courses.courseactivity')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_acknowledgements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ack_timestamp', '-id'],
                'unique_together': {('attempt', 'student')},
            },
        ),
    ]
