# Generated by Django 5.2.7 on 2026-03-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0031_alter_attendancerecord_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseactivity",
            name="allow_answer_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="courseactivity",
            name="show_score_immediately",
            field=models.BooleanField(default=False),
        ),
    ]
