# Generated by Django 5.2.7 on 2026-03-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0032_courseactivity_review_visibility_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradingcomponent",
            name="activity_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="gradingscheme",
            name="custom_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
