# Generated by Django 5.2.7 on 2026-03-07 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_ai', '0001_initial'),
        ('users_app', '0008_course_join_code_course_join_code_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentperformanceprofile',
            index=models.Index(fields=['course', 'student'], name='idx_perf_course_student'),
        ),
        migrations.AddIndex(
            model_name='studentperformanceprofile',
            index=models.Index(fields=['updated_at'], name='idx_perf_updated_at'),
        ),
        migrations.AddIndex(
            model_name='studentriskprediction',
            index=models.Index(fields=['course', 'risk_level'], name='idx_risk_course_level'),
        ),
        migrations.AddIndex(
            model_name='studentriskprediction',
            index=models.Index(fields=['course', 'risk_score'], name='idx_risk_course_score'),
        ),
        migrations.AddIndex(
            model_name='studentriskprediction',
            index=models.Index(fields=['updated_at'], name='idx_risk_updated_at'),
        ),
        migrations.AddConstraint(
            model_name='studentperformanceprofile',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='uq_perf_student_course'),
        ),
        migrations.AddConstraint(
            model_name='studentriskprediction',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='uq_risk_student_course'),
        ),
    ]
