# Generated by Django 5.2.7 on 2026-03-07 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_ai', '0002_studentperformanceprofile_idx_perf_course_student_and_more'),
        ('users_app', '0008_course_join_code_course_join_code_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('average_grade', models.FloatField(default=0.0)),
                ('average_engagement', models.FloatField(default=0.0)),
                ('high_risk_students', models.PositiveIntegerField(default=0)),
                ('medium_risk_students', models.PositiveIntegerField(default=0)),
                ('low_risk_students', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_analytics', to='users_app.course')),
            ],
            options={
                'indexes': [models.Index(fields=['last_updated'], name='idx_course_an_updated'), models.Index(fields=['high_risk_students'], name='idx_course_an_high')],
            },
        ),
        migrations.CreateModel(
            name='StudentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_grade', models.FloatField(default=0.0)),
                ('late_rate', models.FloatField(default=0.0)),
                ('missing_rate', models.FloatField(default=0.0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('grade_trend', models.FloatField(default=0.0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='low', max_length=10)),
                ('probability_student_fails', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_analytics', to='users_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['course', 'risk_level'], name='idx_stu_an_course_level'), models.Index(fields=['course', 'risk_score'], name='idx_stu_an_course_score'), models.Index(fields=['last_updated'], name='idx_stu_an_updated')],
                'constraints': [models.UniqueConstraint(fields=('student', 'course'), name='uq_student_analytics')],
            },
        ),
    ]
