# Generated by Django 5.2.7 on 2026-03-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_ai', '0004_studentanalytics_prediction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanalytics',
            name='total_submissions',
            field=models.IntegerField(default=0),
        ),
    ]
