# Generated by Django 5.2.7 on 2026-03-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_ai', '0005_studentanalytics_total_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanalytics',
            name='risk_explanation',
            field=models.TextField(blank=True),
        ),
    ]
