# Generated by Django 5.2.7 on 2025-11-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_approvedschoolid_user_is_verified_school_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedschoolid',
            name='name',
        ),
        migrations.AddField(
            model_name='approvedschoolid',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='approvedschoolid',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='approvedschoolid',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
