# Generated by Django 5.2.7 on 2025-11-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_remove_approvedschoolid_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedschoolid',
            name='college',
            field=models.CharField(blank=True, choices=[('CAS', 'College of Arts & Sciences'), ('CCJE', 'College of Criminal Justice Education'), ('CAF', 'College of Agriculture & Forestry'), ('CTED', 'College of Teacher Education'), ('CBA', 'College of Business Administration')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='approvedschoolid',
            name='initial_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(blank=True, choices=[('CAS', 'College of Arts & Sciences'), ('CCJE', 'College of Criminal Justice Education'), ('CAF', 'College of Agriculture & Forestry'), ('CTED', 'College of Teacher Education'), ('CBA', 'College of Business Administration')], max_length=10, null=True),
        ),
    ]
