# Generated by Django 5.2.7 on 2025-12-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_course_category_course_description_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedschoolid',
            name='college',
            field=models.CharField(blank=True, choices=[('CAS', 'College of Arts & Sciences'), ('CCJE', 'College of Criminal Justice Education'), ('CAF', 'College of Agriculture & Forestry'), ('CTED', 'College of Teacher Education'), ('CBA', 'College of Business Administration'), ('CIT', 'College of INDUSTRIAL TECHNOLOGY')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.CharField(blank=True, choices=[('CAS', 'College of Arts & Sciences'), ('CCJE', 'College of Criminal Justice Education'), ('CAF', 'College of Agriculture & Forestry'), ('CTED', 'College of Teacher Education'), ('CBA', 'College of Business Administration'), ('CIT', 'College of INDUSTRIAL TECHNOLOGY')], max_length=10, null=True),
        ),
    ]
