# Generated by Django 5.2.7 on 2026-03-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0007_alter_approvedschoolid_college_alter_user_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='join_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='join_code_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
