# Generated by Django 5.2.7 on 2026-04-22 18:50

import users_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0016_notification_event_context'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users_app.models.CustomUserManager()),
            ],
        ),
    ]
