# Generated by Django 6.0 on 2026-05-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0020_alter_sitesettings_require_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
